version: '3.5'

services:
  frontend:
    image: mariaclarinha/adopet-frontend:latest
    container_name: adopet-frontend
    ports:
      - "80:3000"
    networks:
      - adopet
    restart: unless-stopped

  backend:
    image: mariaclarinha/adopet-backend:latest
    container_name: adopet-backend
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - adopet
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: adopet-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: db_adopet
      PGDATA: /data/postgres/new
    volumes:
      - postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - adopet
    restart: unless-stopped

networks:
  adopet:
    driver: bridge

volumes:
  postgres:
